apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bank-churn-api
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      timeoutSeconds: 300
      containers:
        - image: us-central1-docker.pkg.dev/gcp-sandbox-syngenta-mlops/cicd-aiml/bank-churn-model:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"